// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! FFI bindings to UCC (Unified Collective Communication)
//!
//! These bindings are generated at compile time by build.rs

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(improper_ctypes)]

// Include the generated bindings
include!(concat!(env!("OUT_DIR"), "/ucc_bindings.rs"));

// UCC datatype constants (not generated by bindgen as they're C macros)
// Based on ucc/api/ucc_def.h datatype definitions
pub const UCC_DT_INT8: ucc_datatype_t = 0;
pub const UCC_DT_UINT8: ucc_datatype_t = 1;
pub const UCC_DT_INT16: ucc_datatype_t = 2;
pub const UCC_DT_UINT16: ucc_datatype_t = 3;
pub const UCC_DT_INT32: ucc_datatype_t = 4;
pub const UCC_DT_UINT32: ucc_datatype_t = 5;
pub const UCC_DT_INT64: ucc_datatype_t = 6;
pub const UCC_DT_UINT64: ucc_datatype_t = 7;
pub const UCC_DT_FLOAT16: ucc_datatype_t = 8;
pub const UCC_DT_FLOAT32: ucc_datatype_t = 9;
pub const UCC_DT_FLOAT64: ucc_datatype_t = 10;
// UCC_DT_PREDEFINED_LAST is already defined in generated bindings

// UCC memory type constants (not all generated consistently)
pub const UCC_MEMORY_TYPE_HOST: ucc_memory_type = ucc_memory_type_UCC_MEMORY_TYPE_HOST;

// UCC reduction operation constants
pub const UCC_OP_SUM: ucc_reduction_op_t = ucc_reduction_op_t_UCC_OP_SUM;
pub const UCC_OP_PROD: ucc_reduction_op_t = ucc_reduction_op_t_UCC_OP_PROD;
pub const UCC_OP_MAX: ucc_reduction_op_t = ucc_reduction_op_t_UCC_OP_MAX;
pub const UCC_OP_MIN: ucc_reduction_op_t = ucc_reduction_op_t_UCC_OP_MIN;
pub const UCC_OP_LAND: ucc_reduction_op_t = ucc_reduction_op_t_UCC_OP_LAND;
pub const UCC_OP_LOR: ucc_reduction_op_t = ucc_reduction_op_t_UCC_OP_LOR;
pub const UCC_OP_BAND: ucc_reduction_op_t = ucc_reduction_op_t_UCC_OP_BAND;
pub const UCC_OP_BOR: ucc_reduction_op_t = ucc_reduction_op_t_UCC_OP_BOR;
pub const UCC_OP_LAST: ucc_reduction_op_t = ucc_reduction_op_t_UCC_OP_LAST;

// UCC collective type constants
pub const UCC_COLL_TYPE_ALLGATHER: ucc_coll_type_t = ucc_coll_type_t_UCC_COLL_TYPE_ALLGATHER;
pub const UCC_COLL_TYPE_ALLGATHERV: ucc_coll_type_t = ucc_coll_type_t_UCC_COLL_TYPE_ALLGATHERV;
pub const UCC_COLL_TYPE_ALLREDUCE: ucc_coll_type_t = ucc_coll_type_t_UCC_COLL_TYPE_ALLREDUCE;
pub const UCC_COLL_TYPE_BCAST: ucc_coll_type_t = ucc_coll_type_t_UCC_COLL_TYPE_BCAST;
pub const UCC_COLL_TYPE_GATHER: ucc_coll_type_t = ucc_coll_type_t_UCC_COLL_TYPE_GATHER;
pub const UCC_COLL_TYPE_GATHERV: ucc_coll_type_t = ucc_coll_type_t_UCC_COLL_TYPE_GATHERV;

// UCC status constants
pub const UCC_OK: ucc_status_t = ucc_status_t_UCC_OK;
pub const UCC_INPROGRESS: ucc_status_t = ucc_status_t_UCC_INPROGRESS;
pub const UCC_OPERATION_INITIALIZED: ucc_status_t = ucc_status_t_UCC_OPERATION_INITIALIZED;

// UCC library parameter field constants
pub const UCC_LIB_PARAM_FIELD_THREAD_MODE: ucc_lib_params_field = ucc_lib_params_field_UCC_LIB_PARAM_FIELD_THREAD_MODE;

// UCC thread mode constants
pub const UCC_THREAD_SINGLE: ucc_thread_mode_t = ucc_thread_mode_t_UCC_THREAD_SINGLE;

// UCC context parameter field constants
pub const UCC_CONTEXT_PARAM_FIELD_TYPE: ucc_context_params_field = ucc_context_params_field_UCC_CONTEXT_PARAM_FIELD_TYPE;

// UCC context type constants
pub const UCC_CONTEXT_EXCLUSIVE: ucc_context_type_t = ucc_context_type_t_UCC_CONTEXT_EXCLUSIVE;

// UCC team parameter field constants
pub const UCC_TEAM_PARAM_FIELD_EP: ucc_team_params_field = ucc_team_params_field_UCC_TEAM_PARAM_FIELD_EP;
pub const UCC_TEAM_PARAM_FIELD_EP_RANGE: ucc_team_params_field = ucc_team_params_field_UCC_TEAM_PARAM_FIELD_EP_RANGE;

// UCC EP range constants
pub const UCC_COLLECTIVE_EP_RANGE_CONTIG: ucc_ep_range_type_t = ucc_ep_range_type_t_UCC_COLLECTIVE_EP_RANGE_CONTIG;

// UCC collective type - barrier
pub const UCC_COLL_TYPE_BARRIER: ucc_coll_type_t = ucc_coll_type_t_UCC_COLL_TYPE_BARRIER;

// Missing function that bindgen might not have captured
extern "C" {
    pub fn ucc_collective_test(request: ucc_coll_req_h) -> ucc_status_t;
}

/// Wrapper for ucc_init that calls ucc_init_version with the current API version
/// Note: UCC_API_MAJOR and UCC_API_MINOR are defined in generated bindings

/// Initialize UCC library
/// This wraps ucc_init_version to match the C++ ucc_init API
#[inline]
pub unsafe fn ucc_init(
    params: *const ucc_lib_params_t,
    config: ucc_lib_config_h,
    lib_p: *mut ucc_lib_h,
) -> ucc_status_t {
    ucc_init_version(UCC_API_MAJOR, UCC_API_MINOR, params, config, lib_p)
}
