/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Communication backend type */
export const enum CommunicatorType {
  /** FMI backend (Redis/S3 based) */
  Fmi = 'Fmi',
  /** MPI backend (requires MPI runtime) */
  Mpi = 'Mpi',
  /** Libfabric backend (high-performance fabric interface) */
  Libfabric = 'Libfabric',
  /** UCX backend (Unified Communication X) */
  Ucx = 'Ucx',
  /** UCC backend (Unified Collective Communication) */
  Ucc = 'Ucc',
  /** Gloo backend (Facebook's collective communication library) */
  Gloo = 'Gloo'
}
/** Configuration options for creating an FMI communicator */
export interface FmiConfigOptions {
  rank: number
  worldSize: number
  host?: string
  port?: number
  maxTimeout?: number
  commName?: string
  nonblocking?: boolean
  redisHost?: string
  redisPort?: number
  redisNamespace?: string
}
/** Generic communicator configuration */
export interface CommunicatorConfig {
  /** Backend type to use */
  commType: CommunicatorType
  /** FMI-specific options (required if comm_type is Fmi) */
  fmi?: FmiConfigOptions
}
/** Create an FMI communicator (convenience function) */
export declare function createCommunicator(options: FmiConfigOptions): Communicator
/**
 * Communicator wrapper for Node.js
 * Uses the Communicator trait for backend-agnostic operations
 */
export declare class Communicator {
  /** Create a communicator with the specified backend */
  static create(config: CommunicatorConfig): Communicator
  /** Create an FMI communicator (convenience method) */
  static createFmi(options: FmiConfigOptions): Communicator
  /** Get the communication backend type */
  getCommType(): string
  getRank(): number
  getWorldSize(): number
  barrier(): void
  /**
   * All-to-all exchange: partitions[i] goes to worker i
   * This is the key primitive for distributed shuffles.
   */
  allToAll(partitions: Array<Buffer>): Array<Buffer>
  /** Allgather: each worker contributes data, all receive all data */
  allGather(data: Buffer): Array<Buffer>
  /** Broadcast from root to all workers */
  broadcast(data: Buffer, root: number): Buffer
  /**
   * Gather: collect data from all workers to root
   * Implemented using allgather (as per Communicator trait design)
   * Returns results only on root, empty vector on other workers
   */
  gather(data: Buffer, root: number): Array<Buffer>
  /**
   * Scatter: distribute partitions from root to all workers
   * Implemented using all_to_all (as per Communicator trait design)
   * Root sends partition[i] to worker i, returns this worker's partition
   */
  scatter(partitions: Array<Buffer>, root: number): Buffer
  /** Point-to-point send */
  send(data: Buffer, dest: number, tag: number): void
  /** Point-to-point receive */
  recv(source: number, tag: number): Buffer
}
