/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Communication backend type */
export const enum CommunicatorType {
  /** FMI backend (Redis/S3 based) */
  Fmi = 'Fmi',
  /** MPI backend (requires MPI runtime) */
  Mpi = 'Mpi',
  /** Libfabric backend (high-performance fabric interface) */
  Libfabric = 'Libfabric',
  /** UCX backend (Unified Communication X) */
  Ucx = 'Ucx',
  /** UCC backend (Unified Collective Communication) */
  Ucc = 'Ucc',
  /** Gloo backend (Facebook's collective communication library) */
  Gloo = 'Gloo'
}
/** Configuration options for creating an FMI communicator */
export interface FmiConfigOptions {
  rank: number
  worldSize: number
  host?: string
  port?: number
  maxTimeout?: number
  commName?: string
  nonblocking?: boolean
  redisHost?: string
  redisPort?: number
  redisNamespace?: string
}
/** Configuration options for creating a UCX communicator */
export interface UcxConfigOptions {
  /** World size (total number of processes) */
  worldSize: number
  /** Session ID for coordination (unique per job) */
  sessionId: string
  /** Redis host for OOB communication (required, or set REDIS_HOST env var) */
  redisHost?: string
  /** Redis port for OOB communication (required, or set REDIS_PORT env var) */
  redisPort?: number
  /** Enable UCC for collective operations (requires ucc feature) */
  enableUcc?: boolean
}
/** Configuration options for creating a Libfabric communicator */
export interface LibfabricConfigOptions {
  /** World size (total number of processes) */
  worldSize: number
  /** Session ID for coordination (unique per job) */
  sessionId: string
  /** Redis host for OOB communication (required, or set REDIS_HOST env var) */
  redisHost?: string
  /** Redis port for OOB communication (required, or set REDIS_PORT env var) */
  redisPort?: number
  /**
   * Force specific provider (None = auto-select)
   * Examples: "efa", "tcp", "shm", "verbs", "sockets"
   */
  provider?: string
}
/** Generic communicator configuration */
export interface CommunicatorConfig {
  /** Backend type to use */
  commType: CommunicatorType
  /** FMI-specific options (required if comm_type is Fmi) */
  fmi?: FmiConfigOptions
  /** UCX-specific options (required if comm_type is Ucx or Ucc) */
  ucx?: UcxConfigOptions
  /** Libfabric-specific options (required if comm_type is Libfabric) */
  libfabric?: LibfabricConfigOptions
}
/** Create an FMI communicator (convenience function) */
export declare function createCommunicator(options: FmiConfigOptions): Communicator
/**
 * Communicator wrapper for Node.js
 * Uses the Communicator trait for backend-agnostic operations
 */
export declare class Communicator {
  /** Create a communicator with the specified backend */
  static create(config: CommunicatorConfig): Communicator
  /** Create an FMI communicator (convenience method) */
  static createFmi(options: FmiConfigOptions): Communicator
  /** Create a UCX communicator (convenience method) */
  static createUcx(options: UcxConfigOptions): Communicator
  /** Create a Libfabric communicator (convenience method) */
  static createLibfabric(options: LibfabricConfigOptions): Communicator
  /** Get the communication backend type */
  getCommType(): string
  getRank(): number
  getWorldSize(): number
  barrier(): void
  /**
   * All-to-all exchange: partitions[i] goes to worker i
   * This is the key primitive for distributed shuffles.
   */
  allToAll(partitions: Array<Buffer>): Array<Buffer>
  /** Allgather: each worker contributes data, all receive all data */
  allGather(data: Buffer): Array<Buffer>
  /** Broadcast from root to all workers */
  broadcast(data: Buffer, root: number): Buffer
  /**
   * Gather: collect data from all workers to root
   * Implemented using allgather (as per Communicator trait design)
   * Returns results only on root, empty vector on other workers
   */
  gather(data: Buffer, root: number): Array<Buffer>
  /**
   * Scatter: distribute equal-length partitions from root to all workers.
   *
   * Uses the backend's native scatter over its FMI channel — on the Direct
   * channel an O(log P) binomial tree. Root passes `world_size` equal-length
   * partitions; every worker returns its own chunk. Non-root workers pass `[]`.
   */
  scatter(partitions: Array<Buffer>, root: number): Buffer
  /**
   * Scatterv: distribute variable-length partitions from root to all workers.
   *
   * Same contract as `scatter` but the per-worker chunk lengths may differ.
   * Uses the backend's native scatterv over its FMI channel — on the Direct
   * channel an O(log P) binomial tree — the byte counts are broadcast from root,
   * then the concatenated partitions scattered.
   */
  scatterv(partitions: Array<Buffer>, root: number): Buffer
  /**
   * Reduce: element-wise numeric reduce of `data` to `root`.
   *
   * `data` is a flat little-endian array of `dtype` (`f32`|`f64`|`i32`|`i64`);
   * `op` is `sum`|`min`|`max`|`prod`. Uses the backend's native reduce (binomial
   * tree on FMI). Returns the reduced buffer on root and an empty buffer on
   * other workers.
   */
  reduce(data: Buffer, root: number, op: string, dtype: string): Buffer
  /** Point-to-point send */
  send(data: Buffer, dest: number, tag: number): void
  /** Point-to-point receive */
  recv(source: number, tag: number): Buffer
}
