name: Conda C++/Python - gcc,OpenMPI  & GCylon

on:
  push:
    branches:
      - main
      - mirror
      - 0.**
  pull_request:
    branches: 
      - main
      - mirror
      - 0.**

jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      # explicit include-based build matrix, of known valid options
      matrix:
        include:
          # 22.04 supports CUDA 11.0+
          - os: ubuntu-22.04
            cuda: "11.8.0"
            gcc: 11

    steps:
    - uses: actions/checkout@v4

    - name: Clean-up container 
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
    
    # Specify the correct host compilers
    - name: Install/Select gcc and g++
      run: |
        sudo apt-get install -y gcc-${{ matrix.gcc }} g++-${{ matrix.gcc }} autoconf automake libtool
        echo "CC=/usr/bin/gcc-${{ matrix.gcc }}" >> $GITHUB_ENV
        echo "CXX=/usr/bin/g++-${{ matrix.gcc }}" >> $GITHUB_ENV
        echo "CUDAHOSTCXX=/usr/bin/g++-${{ matrix.gcc }}" >> $GITHUB_ENV

    - uses: Jimver/cuda-toolkit@v0.2.16
      id: cuda-toolkit
      with:
        cuda: ${{ matrix.cuda }}

    - uses: conda-incubator/setup-miniconda@v3
      with:
        miniconda-version: "latest"  # You can specify a version or leave it as "latest"
        auto-update-conda: true
        activate-environment: gcylon_dev
        environment-file: conda/environments/gcylon.yml

    - name: Build cylon, pycylon and run cpp test
      run: python build.py -cmake-flags="-DCYLON_UCX=1" -ipath="$HOME/cylon/install" --cpp --python --test

    - name: Run pytest
      run: python build.py -ipath="$HOME/cylon/install" --pytest

    - name: Build gcylon cpp, no testing at github for gpu
      run: ./build.sh --gcylon --release

    - name: Build pygcylon, no testing at github for gpu
      run: ./build.sh --pygcylon --release

